GET http://localhost:3000/parents

###

GET http://localhost:3000/parents/



###

POST http://localhost:3000/parents
Content-type: application/json

{
    "name": "James Justis",
    "childName": "Neville"
}

###

DELETE http://localhost:3000/parents

### 
PATCH http://localhost:3000/parents



